version: 2
updates:
  - package-ecosystem: "github-actions"
    # default location of `.github/workflows`
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget-csharp"
    # location of package manifests
    directory: "/csharp/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "nuget-fsharp"
    # location of package manifests
    directory: "/fsharp/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
